name: Develop workflows
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:
jobs:
  BuildRust:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Aegis"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - run: |  
          echo "The repository ${{ github.repository }} contains the following files"
          tree
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
