name: Develop workflows
on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - develop
  workflow_dispatch:
jobs:
  PreMerge:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building PreMerge ${{ github.repository }}"
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # This checks out the PR's source branch
      - run: |  
          echo "Running on branch: ${{ github.event.pull_request.head.ref }} with commit ${{ github.event.pull_request.head.sha }}"
          echo "The repository ${{ github.repository }} contains the following files"
          tree
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
  PostMerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true # Only run if the PR is merged
    steps:
      - run: echo "Building PostMerge ${{ github.repository }}"
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.base.ref }} # This checks out the PR's target branch
      - name: Fetch latest
        run: git fetch origin ${{ github.event.pull_request.base.ref }}
      - run: |  
          echo "Building on ${{ github.event.pull_request.base.ref }} branch after merge"
          echo "Latest commit on ${{ github.event.pull_request.base.ref }}: $(git rev-parse HEAD)"
          echo "The repository ${{ github.repository }} contains the following files"
          tree
      - name: Build
        run: |
          cargo clean
          cargo build --release --target x86_64-unknown-linux-gnu
      - name: Run tests
        run: cargo test --release --target x86_64-unknown-linux-gnu
